-- ============================================================
-- PostgreSQL schema generated from SQLite (cricket_sim.db)
-- Generated by: scripts/db_schema_export.py
-- DO NOT EDIT MANUALLY — regenerate from source SQLite
-- ============================================================

CREATE TABLE IF NOT EXISTS "users" (
    "id" VARCHAR(120),
    "password_hash" VARCHAR(200),
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "last_login" TIMESTAMP WITHOUT TIME ZONE,
    "ip_address" VARCHAR(50),
    "mac_address" VARCHAR(50),
    "hostname" VARCHAR(100),
    "display_name" VARCHAR(100),
    "stable_id" VARCHAR(36),
    "is_admin" BOOLEAN NOT NULL DEFAULT FALSE,
    "is_banned" BOOLEAN NOT NULL DEFAULT FALSE,
    "banned_until" TIMESTAMP WITHOUT TIME ZONE,
    "ban_reason" VARCHAR(500),
    "force_password_reset" BOOLEAN NOT NULL DEFAULT FALSE,
    "email_verified" INTEGER NOT NULL DEFAULT FALSE,
    "email_verify_token" TEXT,
    "email_verify_token_expires" TIMESTAMP WITHOUT TIME ZONE,
    "reset_token" TEXT,
    "reset_token_expires" TIMESTAMP WITHOUT TIME ZONE,
    "verify_resend_count" INTEGER NOT NULL DEFAULT FALSE,
    "verify_resend_window_start" TIMESTAMP WITHOUT TIME ZONE,
    "force_email_verify" BOOLEAN NOT NULL DEFAULT FALSE,
    "lockout_until" TIMESTAMP WITHOUT TIME ZONE,
    "lockout_count" INTEGER NOT NULL DEFAULT FALSE,
    "lockout_window_start" TIMESTAMP WITHOUT TIME ZONE,
    "pending_email" VARCHAR(120),
    "pending_email_token" VARCHAR(64),
    "pending_email_token_expires" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_users_is_admin" ON "users" ("is_admin");
CREATE INDEX IF NOT EXISTS "ix_users_pending_email_token" ON "users" ("pending_email_token");

CREATE TABLE IF NOT EXISTS "teams" (
    "id" SERIAL,
    "user_id" VARCHAR(120) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "short_code" VARCHAR(10) NOT NULL,
    "home_ground" VARCHAR(100),
    "pitch_preference" VARCHAR(50),
    "team_color" VARCHAR(20),
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "is_draft" BOOLEAN,
    "is_placeholder" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_teams_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


CREATE TABLE IF NOT EXISTS "team_profiles" (
    "id" SERIAL,
    "team_id" INTEGER NOT NULL,
    "format_type" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_team_profiles_team_id_format_type" UNIQUE ("team_id", "format_type"),
    CONSTRAINT "fk_team_profiles_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id")
);

CREATE INDEX IF NOT EXISTS "ix_team_profiles_team_id" ON "team_profiles" ("team_id");

CREATE TABLE IF NOT EXISTS "players" (
    "id" SERIAL,
    "team_id" INTEGER NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "role" VARCHAR(50),
    "batting_rating" INTEGER,
    "bowling_rating" INTEGER,
    "fielding_rating" INTEGER,
    "batting_hand" VARCHAR(20),
    "bowling_type" VARCHAR(50),
    "bowling_hand" VARCHAR(20),
    "is_captain" BOOLEAN,
    "is_wicketkeeper" BOOLEAN,
    "matches_played" INTEGER,
    "total_runs" INTEGER,
    "total_balls_faced" INTEGER,
    "total_fours" INTEGER,
    "total_sixes" INTEGER,
    "total_fifties" INTEGER,
    "total_centuries" INTEGER,
    "highest_score" INTEGER,
    "not_outs" INTEGER,
    "total_balls_bowled" INTEGER,
    "total_runs_conceded" INTEGER,
    "total_wickets" INTEGER,
    "total_maidens" INTEGER,
    "five_wicket_hauls" INTEGER,
    "best_bowling_wickets" INTEGER,
    "best_bowling_runs" INTEGER,
    "profile_id" INTEGER,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_players_profile_id_name" UNIQUE ("profile_id", "name"),
    CONSTRAINT "fk_players_profile_id" FOREIGN KEY ("profile_id") REFERENCES "team_profiles" ("id"),
    CONSTRAINT "fk_players_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id")
);

CREATE INDEX IF NOT EXISTS "ix_players_profile_id" ON "players" ("profile_id");
CREATE INDEX IF NOT EXISTS "ix_players_team_id" ON "players" ("team_id");

CREATE TABLE IF NOT EXISTS "tournaments" (
    "id" SERIAL,
    "user_id" VARCHAR(120) NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "status" VARCHAR(20),
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "mode" VARCHAR(50) NOT NULL,
    "current_stage" VARCHAR(30) NOT NULL,
    "playoff_teams" INTEGER NOT NULL,
    "series_config" TEXT,
    "format_type" VARCHAR(20) NOT NULL DEFAULT T20,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_tournaments_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


CREATE TABLE IF NOT EXISTS "matches" (
    "id" VARCHAR(36),
    "user_id" VARCHAR(120),
    "home_team_id" INTEGER,
    "away_team_id" INTEGER,
    "winner_team_id" INTEGER,
    "tournament_id" INTEGER,
    "venue" VARCHAR(100),
    "pitch_type" VARCHAR(50),
    "date" TIMESTAMP WITHOUT TIME ZONE,
    "result_description" VARCHAR(200),
    "home_team_score" INTEGER,
    "home_team_wickets" INTEGER,
    "home_team_overs" DOUBLE PRECISION,
    "away_team_score" INTEGER,
    "away_team_wickets" INTEGER,
    "away_team_overs" DOUBLE PRECISION,
    "match_json_path" VARCHAR(255),
    "toss_winner_team_id" INTEGER,
    "toss_decision" VARCHAR(10),
    "margin_type" TEXT,
    "margin_value" INTEGER,
    "match_format" TEXT DEFAULT T20,
    "overs_per_side" INTEGER DEFAULT 20,
    "is_day_night" BOOLEAN DEFAULT FALSE,
    "fc_days" INTEGER,
    "fc_innings_json" TEXT,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_matches_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id"),
    CONSTRAINT "fk_matches_home_team_id" FOREIGN KEY ("home_team_id") REFERENCES "teams" ("id"),
    CONSTRAINT "fk_matches_away_team_id" FOREIGN KEY ("away_team_id") REFERENCES "teams" ("id"),
    CONSTRAINT "fk_matches_winner_team_id" FOREIGN KEY ("winner_team_id") REFERENCES "teams" ("id"),
    CONSTRAINT "fk_matches_tournament_id" FOREIGN KEY ("tournament_id") REFERENCES "tournaments" ("id"),
    CONSTRAINT "fk_matches_toss_winner_team_id" FOREIGN KEY ("toss_winner_team_id") REFERENCES "teams" ("id")
);


CREATE TABLE IF NOT EXISTS "match_scorecards" (
    "id" SERIAL,
    "match_id" VARCHAR(36) NOT NULL,
    "player_id" INTEGER NOT NULL,
    "team_id" INTEGER NOT NULL,
    "runs" INTEGER,
    "balls" INTEGER,
    "fours" INTEGER,
    "sixes" INTEGER,
    "is_out" BOOLEAN,
    "wicket_type" VARCHAR(50),
    "overs" DOUBLE PRECISION,
    "balls_bowled" INTEGER,
    "runs_conceded" INTEGER,
    "wickets" INTEGER,
    "maidens" INTEGER,
    "wides" INTEGER,
    "noballs" INTEGER,
    "catches" INTEGER,
    "run_outs" INTEGER,
    "wicket_taker_name" VARCHAR(100),
    "fielder_name" VARCHAR(100),
    "innings_number" INTEGER NOT NULL DEFAULT TRUE,
    "record_type" VARCHAR(20) NOT NULL DEFAULT batting,
    "position" INTEGER,
    "ones" INTEGER DEFAULT FALSE,
    "twos" INTEGER DEFAULT FALSE,
    "threes" INTEGER DEFAULT FALSE,
    "dot_balls" INTEGER DEFAULT FALSE,
    "strike_rate" REAL DEFAULT 0.0,
    "batting_position" INTEGER,
    "dot_balls_bowled" INTEGER DEFAULT FALSE,
    "wickets_bowled" INTEGER DEFAULT FALSE,
    "wickets_caught" INTEGER DEFAULT FALSE,
    "wickets_lbw" INTEGER DEFAULT FALSE,
    "wickets_stumped" INTEGER DEFAULT FALSE,
    "wickets_run_out" INTEGER DEFAULT FALSE,
    "wickets_hit_wicket" INTEGER DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_match_scorecards_match_id" FOREIGN KEY ("match_id") REFERENCES "matches" ("id"),
    CONSTRAINT "fk_match_scorecards_player_id" FOREIGN KEY ("player_id") REFERENCES "players" ("id"),
    CONSTRAINT "fk_match_scorecards_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id")
);


CREATE TABLE IF NOT EXISTS "match_partnerships" (
    "id" SERIAL,
    "match_id" VARCHAR(36) NOT NULL,
    "innings_number" INTEGER NOT NULL,
    "wicket_number" INTEGER NOT NULL,
    "batsman1_id" INTEGER NOT NULL,
    "batsman2_id" INTEGER NOT NULL,
    "runs" INTEGER,
    "balls" INTEGER,
    "batsman1_contribution" INTEGER,
    "batsman2_contribution" INTEGER,
    "start_over" DOUBLE PRECISION,
    "end_over" DOUBLE PRECISION,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_match_partnerships_match_id" FOREIGN KEY ("match_id") REFERENCES "matches" ("id"),
    CONSTRAINT "fk_match_partnerships_batsman1_id" FOREIGN KEY ("batsman1_id") REFERENCES "players" ("id"),
    CONSTRAINT "fk_match_partnerships_batsman2_id" FOREIGN KEY ("batsman2_id") REFERENCES "players" ("id")
);

CREATE INDEX IF NOT EXISTS "ix_partnership_match_innings" ON "match_partnerships" ("match_id", "innings_number");

CREATE TABLE IF NOT EXISTS "tournament_teams" (
    "id" SERIAL,
    "tournament_id" INTEGER NOT NULL,
    "team_id" INTEGER NOT NULL,
    "played" INTEGER NOT NULL,
    "won" INTEGER NOT NULL,
    "lost" INTEGER NOT NULL,
    "tied" INTEGER NOT NULL,
    "no_result" INTEGER NOT NULL,
    "points" INTEGER NOT NULL,
    "runs_scored" INTEGER NOT NULL,
    "overs_faced" DOUBLE PRECISION NOT NULL,
    "runs_conceded" INTEGER NOT NULL,
    "overs_bowled" DOUBLE PRECISION NOT NULL,
    "net_run_rate" DOUBLE PRECISION NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_tournament_team" UNIQUE ("tournament_id", "team_id"),
    CONSTRAINT "fk_tournament_teams_tournament_id" FOREIGN KEY ("tournament_id") REFERENCES "tournaments" ("id"),
    CONSTRAINT "fk_tournament_teams_team_id" FOREIGN KEY ("team_id") REFERENCES "teams" ("id")
);


CREATE TABLE IF NOT EXISTS "tournament_fixtures" (
    "id" SERIAL,
    "tournament_id" INTEGER NOT NULL,
    "home_team_id" INTEGER,
    "away_team_id" INTEGER,
    "round_number" INTEGER NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "stage" VARCHAR(30) NOT NULL,
    "stage_description" VARCHAR(100),
    "bracket_position" INTEGER,
    "match_id" VARCHAR(36),
    "winner_team_id" INTEGER,
    "series_match_number" INTEGER,
    "standings_applied" BOOLEAN NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_tournament_fixtures_tournament_id" FOREIGN KEY ("tournament_id") REFERENCES "tournaments" ("id"),
    CONSTRAINT "fk_tournament_fixtures_home_team_id" FOREIGN KEY ("home_team_id") REFERENCES "teams" ("id"),
    CONSTRAINT "fk_tournament_fixtures_away_team_id" FOREIGN KEY ("away_team_id") REFERENCES "teams" ("id"),
    CONSTRAINT "fk_tournament_fixtures_match_id" FOREIGN KEY ("match_id") REFERENCES "matches" ("id"),
    CONSTRAINT "fk_tournament_fixtures_winner_team_id" FOREIGN KEY ("winner_team_id") REFERENCES "teams" ("id")
);

CREATE INDEX IF NOT EXISTS "ix_fixture_tournament_stage" ON "tournament_fixtures" ("tournament_id", "stage");
CREATE INDEX IF NOT EXISTS "ix_fixture_tournament_status" ON "tournament_fixtures" ("tournament_id", "status");

CREATE TABLE IF NOT EXISTS "tournament_player_stats_cache" (
    "id" SERIAL,
    "tournament_id" INTEGER NOT NULL,
    "player_id" INTEGER NOT NULL,
    "category" VARCHAR(20) NOT NULL,
    "data_json" TEXT NOT NULL,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE,
    "team_id" INTEGER,
    "matches_played" INTEGER DEFAULT FALSE,
    "innings_batted" INTEGER DEFAULT FALSE,
    "runs_scored" INTEGER DEFAULT FALSE,
    "balls_faced" INTEGER DEFAULT FALSE,
    "fours" INTEGER DEFAULT FALSE,
    "sixes" INTEGER DEFAULT FALSE,
    "not_outs" INTEGER DEFAULT FALSE,
    "highest_score" INTEGER DEFAULT FALSE,
    "fifties" INTEGER DEFAULT FALSE,
    "centuries" INTEGER DEFAULT FALSE,
    "batting_average" DOUBLE PRECISION DEFAULT 0.0,
    "batting_strike_rate" DOUBLE PRECISION DEFAULT 0.0,
    "innings_bowled" INTEGER DEFAULT FALSE,
    "overs_bowled" VARCHAR(10) DEFAULT 0.0,
    "runs_conceded" INTEGER DEFAULT FALSE,
    "wickets_taken" INTEGER DEFAULT FALSE,
    "maidens" INTEGER DEFAULT FALSE,
    "best_bowling_wickets" INTEGER DEFAULT FALSE,
    "best_bowling_runs" INTEGER DEFAULT FALSE,
    "five_wicket_hauls" INTEGER DEFAULT FALSE,
    "bowling_average" DOUBLE PRECISION DEFAULT 0.0,
    "bowling_economy" DOUBLE PRECISION DEFAULT 0.0,
    "bowling_strike_rate" DOUBLE PRECISION DEFAULT 0.0,
    "catches" INTEGER DEFAULT FALSE,
    "run_outs" INTEGER DEFAULT FALSE,
    "stumpings" INTEGER DEFAULT FALSE,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_tournament_player_stats_cache_tournament_id" FOREIGN KEY ("tournament_id") REFERENCES "tournaments" ("id"),
    CONSTRAINT "fk_tournament_player_stats_cache_player_id" FOREIGN KEY ("player_id") REFERENCES "players" ("id")
);


CREATE TABLE IF NOT EXISTS "failed_login_attempts" (
    "id" SERIAL,
    "email" VARCHAR(120) NOT NULL,
    "ip_address" VARCHAR(50),
    "user_agent" VARCHAR(300),
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_failed_login_attempts_email" ON "failed_login_attempts" ("email");
CREATE INDEX IF NOT EXISTS "ix_failed_login_attempts_timestamp" ON "failed_login_attempts" ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_failed_login_ip" ON "failed_login_attempts" ("ip_address");

CREATE TABLE IF NOT EXISTS "blocked_ips" (
    "id" SERIAL,
    "ip_address" VARCHAR(50) NOT NULL,
    "reason" VARCHAR(300),
    "blocked_by" VARCHAR(120) NOT NULL,
    "blocked_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_blocked_ips_ip_address" UNIQUE ("ip_address")
);


CREATE TABLE IF NOT EXISTS "active_sessions" (
    "id" SERIAL,
    "session_token" VARCHAR(64) NOT NULL,
    "user_id" VARCHAR(120) NOT NULL,
    "ip_address" VARCHAR(50),
    "user_agent" VARCHAR(300),
    "login_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "last_active" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_active_sessions_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);

CREATE INDEX IF NOT EXISTS "ix_active_sessions_user_id" ON "active_sessions" ("user_id");

CREATE TABLE IF NOT EXISTS "site_counters" (
    "key" VARCHAR(50),
    "value" INTEGER NOT NULL,
    PRIMARY KEY ("key")
);


CREATE TABLE IF NOT EXISTS "announcement_banner" (
    "id" SERIAL,
    "message" TEXT NOT NULL,
    "is_enabled" BOOLEAN NOT NULL,
    "version" INTEGER NOT NULL,
    "updated_by" VARCHAR(120),
    "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "color_preset" VARCHAR(20) DEFAULT urgent,
    "position" VARCHAR(10) DEFAULT bottom,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_announcement_banner_updated_by" FOREIGN KEY ("updated_by") REFERENCES "users" ("id")
);


CREATE TABLE IF NOT EXISTS "user_banner_dismissals" (
    "id" SERIAL,
    "user_id" VARCHAR(120) NOT NULL,
    "banner_version" INTEGER NOT NULL,
    "dismissed_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_user_banner_dismissal" UNIQUE ("user_id", "banner_version"),
    CONSTRAINT "fk_user_banner_dismissals_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "ix_user_banner_dismissal_user_ver" ON "user_banner_dismissals" ("user_id", "banner_version");
CREATE INDEX IF NOT EXISTS "ix_user_banner_dismissals_user_id" ON "user_banner_dismissals" ("user_id");

CREATE TABLE IF NOT EXISTS "login_history" (
    "id" SERIAL,
    "user_id" VARCHAR(120) NOT NULL,
    "ip_address" VARCHAR(50),
    "user_agent" VARCHAR(300),
    "event" VARCHAR(10) NOT NULL,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_login_history_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "ix_login_history_user_id" ON "login_history" ("user_id");
CREATE INDEX IF NOT EXISTS "ix_login_history_user_ts" ON "login_history" ("user_id", "timestamp");

CREATE TABLE IF NOT EXISTS "ip_whitelist" (
    "id" SERIAL,
    "ip_address" VARCHAR(50) NOT NULL,
    "label" VARCHAR(100),
    "added_by" VARCHAR(120) NOT NULL,
    "added_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "uq_ip_whitelist_ip_address" UNIQUE ("ip_address")
);


CREATE TABLE IF NOT EXISTS "user_ground_configs" (
    "id" SERIAL,
    "user_id" VARCHAR(120) NOT NULL,
    "config_json" JSONB NOT NULL,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_user_ground_configs_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id")
);


CREATE TABLE IF NOT EXISTS "auth_event_log" (
    "id" SERIAL,
    "event_type" VARCHAR(30) NOT NULL,
    "email" VARCHAR(120) NOT NULL,
    "user_id" VARCHAR(120),
    "details" TEXT,
    "ip_address" VARCHAR(50),
    "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "status" VARCHAR(20) NOT NULL,
    "admin_notes" TEXT,
    "resolved_at" TIMESTAMP WITHOUT TIME ZONE,
    "resolved_by" VARCHAR(120),
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_auth_event_log_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS "ix_auth_event_log_created_at" ON "auth_event_log" ("created_at");
CREATE INDEX IF NOT EXISTS "ix_auth_event_log_email" ON "auth_event_log" ("email");
CREATE INDEX IF NOT EXISTS "ix_auth_event_log_event_type" ON "auth_event_log" ("event_type");
CREATE INDEX IF NOT EXISTS "ix_auth_event_log_status_type" ON "auth_event_log" ("status", "event_type");

CREATE TABLE IF NOT EXISTS "exception_log" (
    "id" SERIAL,
    "exception_type" VARCHAR(200) NOT NULL,
    "exception_message" TEXT NOT NULL,
    "traceback" TEXT,
    "module" VARCHAR(200),
    "function" VARCHAR(200),
    "line_number" INTEGER,
    "filename" VARCHAR(300),
    "user_email" VARCHAR(120),
    "severity" VARCHAR(10) NOT NULL,
    "source" VARCHAR(30) NOT NULL,
    "context_json" TEXT,
    "request_id" VARCHAR(64),
    "handled" BOOLEAN NOT NULL,
    "resolved" BOOLEAN NOT NULL,
    "resolved_at" TIMESTAMP WITHOUT TIME ZONE,
    "resolved_by" VARCHAR(120),
    "fingerprint" VARCHAR(64),
    "occurrence_count" INTEGER NOT NULL,
    "first_seen_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "last_seen_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "github_issue_number" INTEGER,
    "github_issue_url" VARCHAR(300),
    "github_sync_status" VARCHAR(20),
    "github_sync_error" TEXT,
    "github_last_synced_at" TIMESTAMP WITHOUT TIME ZONE,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_exception_fingerprint" ON "exception_log" ("fingerprint");
CREATE INDEX IF NOT EXISTS "ix_exception_resolved_ts" ON "exception_log" ("resolved", "timestamp");
CREATE INDEX IF NOT EXISTS "ix_exception_source_ts" ON "exception_log" ("source", "timestamp");
CREATE INDEX IF NOT EXISTS "ix_exception_timestamp" ON "exception_log" ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_exception_type_ts" ON "exception_log" ("exception_type", "timestamp");

CREATE TABLE IF NOT EXISTS "issue_report" (
    "id" SERIAL,
    "public_id" VARCHAR(16) NOT NULL,
    "user_email" VARCHAR(120) NOT NULL,
    "category" VARCHAR(30) NOT NULL,
    "title" VARCHAR(200) NOT NULL,
    "description" TEXT NOT NULL,
    "page_url" VARCHAR(500),
    "user_agent" VARCHAR(500),
    "app_version" VARCHAR(50),
    "session_logs_json" TEXT,
    "linked_exception_log_ids" TEXT,
    "github_issue_number" INTEGER,
    "github_issue_url" VARCHAR(300),
    "github_sync_status" VARCHAR(20) NOT NULL,
    "github_sync_error" TEXT,
    "github_last_synced_at" TIMESTAMP WITHOUT TIME ZONE,
    "status" VARCHAR(20) NOT NULL,
    "severity" VARCHAR(20),
    "admin_notes" TEXT,
    "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_issue_report_created_at" ON "issue_report" ("created_at");
CREATE INDEX IF NOT EXISTS "ix_issue_report_github_issue_number" ON "issue_report" ("github_issue_number");
CREATE INDEX IF NOT EXISTS "ix_issue_report_status" ON "issue_report" ("status");
CREATE INDEX IF NOT EXISTS "ix_issue_report_status_created" ON "issue_report" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "ix_issue_report_user_created" ON "issue_report" ("user_email", "created_at");
CREATE INDEX IF NOT EXISTS "ix_issue_report_user_email" ON "issue_report" ("user_email");

CREATE TABLE IF NOT EXISTS "issue_webhook_event" (
    "id" SERIAL,
    "delivery_id" VARCHAR(100) NOT NULL,
    "event_type" VARCHAR(50),
    "action" VARCHAR(50),
    "github_issue_number" INTEGER,
    "payload_json" TEXT,
    "signature_valid" BOOLEAN NOT NULL,
    "processed" BOOLEAN NOT NULL,
    "processing_error" TEXT,
    "received_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_issue_webhook_event_github_issue_number" ON "issue_webhook_event" ("github_issue_number");
CREATE INDEX IF NOT EXISTS "ix_issue_webhook_event_issue_number" ON "issue_webhook_event" ("github_issue_number");

CREATE TABLE IF NOT EXISTS "admin_audit_log" (
    "id" SERIAL,
    "admin_email" VARCHAR(120) NOT NULL,
    "action" VARCHAR(50) NOT NULL,
    "target" VARCHAR(200),
    "details" TEXT,
    "ip_address" VARCHAR(50),
    "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "ix_admin_audit_log_admin_email" ON "admin_audit_log" ("admin_email");
CREATE INDEX IF NOT EXISTS "ix_admin_audit_log_timestamp" ON "admin_audit_log" ("timestamp");
CREATE INDEX IF NOT EXISTS "ix_audit_admin_action" ON "admin_audit_log" ("admin_email", "action");
