"""Frontier fit dataset: measure the FC ball engine's rate/risk response.

Runs first innings with batting intent PINNED at fixed aggression levels and
records, per delivery, the state the engine was in and what it produced. The
aggregated cells are the training data for engine/fc_forecast.py's frontier.

The point is that the captain's forward model must be a compression of THIS
engine rather than a second, independently hand-tuned model of cricket. So
the dataset is generated by the engine itself, and Stage B's fit is checked
back against it.

Run from project root:  python scripts/fc_sweep.py --innings 6
"""
import argparse
import collections
import copy
import json
import logging
import os
import random
import sys
import uuid

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

logging.disable(logging.CRITICAL)

import engine.match as match_module
from engine import fc_declaration
from engine.fc_batting_intent import ability
from scripts.bench_fc import ENGINE_SOURCE_HASH, PITCHES, _squad

match_module.print = lambda *a, **k: None


# Aggression levels to pin. -1 is a full rearguard, +1 is maximum attack.
# batting_intent() returns survival/attack as an exclusive pair, so an
# aggression level maps onto exactly one of them.
AGGRESSION_LEVELS = (-1.0, -0.5, 0.0, 0.5, 1.0)

# Batting side / bowling side squad tiers. Asymmetric pairs are what put
# spread on the strength axis; two symmetric tiers alone give the fit only
# two points to work with and it cannot separate batting from bowling.
MATCHUPS = (
    ("standard", "standard"),
    ("elite", "elite"),
    ("elite", "standard"),
    ("standard", "elite"),
)

# Ball-age buckets in overs: new ball, shine gone, old, due/reversing.
BALL_AGE_EDGES = (10, 25, 50)


def pin(aggression):
    """An intent dict at a fixed aggression, overriding the live policy."""
    return {
        "survival": max(0.0, -aggression),
        "attack": max(0.0, aggression),
        "neutral": 1.0 - abs(aggression),
        "stumps": 0.0,
        "reason": f"sweep@{aggression:+.1f}",
    }


def ball_age_bucket(overs):
    for index, edge in enumerate(BALL_AGE_EDGES):
        if overs < edge:
            return index
    return len(BALL_AGE_EDGES)


def wear_bucket(wear):
    return round(max(0.0, min(1.0, wear)) * 5) / 5


def strength_bucket(diff):
    """Batting-minus-bowling strength, in 10-point bins."""
    return int(round(diff / 10.0)) * 10


class Observer:
    """Records pre-delivery state and the delivery's outcome.

    _update_partnership_tracking runs after the delivery is resolved but
    before the score and wicket count are applied, so self.wickets and
    self.score still hold the pre-delivery values — exactly the state the
    captain would have been reasoning about.
    """

    def __init__(self, match, cells, aggression, attack_strength):
        self.match = match
        self.cells = cells
        self.aggression = aggression
        self.attack_strength = attack_strength
        self.original = match._update_partnership_tracking
        match._update_partnership_tracking = self.observe
        # Innings totals accumulated here rather than read off the match at
        # the end: by the time next_ball() reports innings_end the transition
        # has already reset score/current_over for the innings that follows.
        self.total_runs = self.total_legal = self.total_wickets = 0

    def remaining_strength(self):
        m = self.match
        batters = [m.current_striker, m.current_non_striker] + [
            m.batting_team[i] for i in m.remaining_batter_indices]
        return sum(ability(p) for p in batters) / max(1, len(batters))

    def observe(self, outcome):
        m = self.match
        delivery = outcome["delivery"]
        strength = self.remaining_strength()
        key = (
            m.pitch,
            self.aggression,
            10 - m.wickets,
            wear_bucket(m._compute_pitch_wear()),
            ball_age_bucket(m.fc_ball_overs_bowled),
            strength_bucket(strength - self.attack_strength),
        )
        cell = self.cells[key]
        cell["legal_balls"] += int(delivery["legal"])
        cell["runs"] += delivery["total_runs"]
        cell["wickets"] += int(bool(outcome.get("batter_out")))
        cell["strength_sum"] += strength
        cell["samples"] += 1
        self.total_legal += int(delivery["legal"])
        self.total_runs += delivery["total_runs"]
        self.total_wickets += int(bool(outcome.get("batter_out")))
        self.original(outcome)

    def release(self):
        self.match._update_partnership_tracking = self.original


def _match(pitch, seed, bat_tier, bowl_tier):
    """One FC match set up so the side batting first carries bat_tier."""
    random.seed(seed)
    return match_module.Match({
        "match_id": str(uuid.uuid4()), "created_by": "sweep",
        "timestamp": "2026-08-09T12:00:00",
        "team_home": "HOM_sweep", "team_away": "AWY_sweep",
        "stadium": "Sweep Ground", "pitch": pitch,
        "toss": "Heads", "toss_winner": "HOM", "toss_decision": "Bat",
        "match_format": "FC", "days": 5, "simulation_mode": "auto",
        "is_day_night": False,
        "playing_xi": {"home": copy.deepcopy(_squad("HOM", bat_tier)),
                       "away": copy.deepcopy(_squad("AWY", bowl_tier))},
        "substitutes": {"home": [], "away": []},
        # Clear throughout: weather interruptions add variance to the
        # over count without telling us anything about the frontier.
        "weather_forecast": "clear",
    })


def sweep_innings(pitch, seed, aggression, bat_tier, bowl_tier, cells, limit=8000):
    """One first innings at pinned aggression, run to all out."""
    m = _match(pitch, seed, bat_tier, bowl_tier)
    m.fc_intent_override = pin(aggression)
    attack = [p for p in m.bowling_team if p.get("will_bowl")]
    attack_strength = sum(p["bowling_rating"] for p in attack) / max(1, len(attack))
    observer = Observer(m, cells, aggression, attack_strength)

    original = fc_declaration.should_declare
    fc_declaration.should_declare = lambda **kw: False
    try:
        for _ in range(limit):
            response = m.next_ball()
            if "error" in response:
                raise RuntimeError(f"sweep {pitch}/{seed}: {response['error']}")
            if response.get("innings_end") or response.get("match_over"):
                return {"runs": observer.total_runs,
                        "wickets": observer.total_wickets,
                        "overs": observer.total_legal / 6.0}
        raise RuntimeError(f"sweep {pitch}/{seed}: innings did not end in {limit} balls")
    finally:
        fc_declaration.should_declare = original
        observer.release()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--innings", type=int, default=6,
                        help="innings per pitch x aggression x matchup cell")
    parser.add_argument("--seed-start", type=int, default=1)
    parser.add_argument("--out", default=os.path.join(
        os.path.dirname(__file__), "..", "reports", "fc_frontier_dataset.json"))
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    cells = collections.defaultdict(
        lambda: {"legal_balls": 0, "runs": 0, "wickets": 0,
                 "strength_sum": 0.0, "samples": 0})
    innings_rows = []

    total = len(PITCHES) * len(AGGRESSION_LEVELS) * len(MATCHUPS) * args.innings
    done = 0
    for pitch in PITCHES:
        for aggression in AGGRESSION_LEVELS:
            for bat_tier, bowl_tier in MATCHUPS:
                for offset in range(args.innings):
                    seed = args.seed_start + offset
                    result = sweep_innings(pitch, seed, aggression,
                                           bat_tier, bowl_tier, cells)
                    innings_rows.append(dict(
                        pitch=pitch, aggression=aggression, seed=seed,
                        bat_tier=bat_tier, bowl_tier=bowl_tier, **result))
                    done += 1
                    print(f"\r{done}/{total} innings", end="", file=sys.stderr)
    print(file=sys.stderr)

    rows = []
    for key, cell in sorted(cells.items()):
        pitch, aggression, wickets_in_hand, wear, age, diff = key
        overs = cell["legal_balls"] / 6.0
        if overs <= 0:
            continue
        rows.append(dict(
            pitch=pitch, aggression=aggression, wickets_in_hand=wickets_in_hand,
            wear=wear, ball_age_bucket=age, strength_diff=diff,
            legal_balls=cell["legal_balls"], runs=cell["runs"],
            wickets=cell["wickets"],
            mean_strength=cell["strength_sum"] / cell["samples"],
            rate=cell["runs"] / overs, wicket_rate=cell["wickets"] / overs))

    report = dict(
        metadata=dict(engine_source_hash=ENGINE_SOURCE_HASH,
                      arguments=vars(args), python=sys.version,
                      aggression_levels=list(AGGRESSION_LEVELS),
                      matchups=[list(m) for m in MATCHUPS],
                      ball_age_edges=list(BALL_AGE_EDGES)),
        innings=innings_rows, cells=rows)

    path = os.path.abspath(args.out)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w" if args.overwrite else "x") as handle:
        json.dump(report, handle, indent=2)

    print(f"Wrote {len(rows)} cells from {len(innings_rows)} innings to {path}\n")
    print(f"{'pitch':<7} {'aggr':>5} {'innings':>8} {'runs':>7} {'overs':>7} {'RPO':>6} {'w/over':>7}")
    for pitch in PITCHES:
        for aggression in AGGRESSION_LEVELS:
            sel = [r for r in innings_rows
                   if r["pitch"] == pitch and r["aggression"] == aggression]
            if not sel:
                continue
            runs = sum(r["runs"] for r in sel)
            overs = sum(r["overs"] for r in sel)
            wkts = sum(r["wickets"] for r in sel)
            print(f"{pitch:<7} {aggression:>+5.1f} {len(sel):>8} "
                  f"{runs/len(sel):>7.0f} {overs/len(sel):>7.1f} "
                  f"{runs/max(overs,1):>6.2f} {wkts/max(overs,1):>7.3f}")


if __name__ == "__main__":
    main()
